name: weather_app
description: A Weather app project along with api.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  dio: ^5.4.0
  
  flutter_bloc: ^8.1.3
  
  bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #dateFormat
  intl: ^0.19.0

  freezed_annotation: ^2.4.1
  
  get_it: ^7.6.4
  
  geocoding: ^2.1.1
  
  geolocator: ^10.1.0
  rive: ^0.12.3
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  

flutter:
  uses-material-design: true
  assets:
   - assets/